version: '3.3'

services:
  calendar-bot:
    build: .
    container_name: calendar-bot
    ports:
      - "8888:8888"
    env_file:
      - deploy/config.env
    volumes:
      - /tmp/calendar-bot/tokens:/tmp/calendar-bot/tokens